name: Run Blog list Python script and commit changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # this is required to fetch all branches

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./src/requirements.txt

    - name: Run Python script
      run: |
        cd src
        python3 ./blog_lists.py

    - name: Commit and push if it changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git add -A ; git commit -m "chore: run blog_list.py script" ; git push origin HEAD:${{ github.head_ref }})
